name: Setup Gleam
description: Set up an Elixir/OTP environment and add it to the PATH
author: Louis Pilfold <louis@lpil.uk>
branding:
  color: pink
  icon: pink
inputs:
  gleam-version:
    description: Version of Gleam to install
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.gleam-version }}
