name: Setup Gleam
description: Set up an Elixir/OTP environment and add it to the PATH
author: Louis Pilfold <louis@lpil.uk>
branding:
  color: pink
  icon: pink
inputs:
  gleam-version:
    description: Version range or exact version of Gleam to use
  otp-version:
    description: Version range or exact version of OTP to use
runs:
  using: node12
  main: src/setup-gleam.js
